# Generated by Django 2.2.10 on 2020-05-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_url', models.CharField(max_length=50)),
                ('save_title', models.CharField(max_length=50)),
                ('save_h1', models.CharField(max_length=50)),
                ('save_encoding', models.CharField(max_length=50)),
                ('seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.CharField(max_length=50, verbose_name='Введите Url')),
                ('input_minutes', models.IntegerField(default=0, verbose_name='минут')),
                ('input_seconds', models.IntegerField(default=0, verbose_name='секунд')),
            ],
            options={
                'verbose_name': 'Ввод url-ов',
                'verbose_name_plural': 'Ввод url-ов',
            },
        ),
    ]
