# Generated by Django 2.2.7 on 2019-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.CharField(max_length=50, verbose_name='Введите Url')),
                ('search_title', models.CharField(default='', max_length=50, verbose_name='Title')),
                ('search_h1', models.CharField(default='', max_length=50, verbose_name='h1')),
                ('search_encoding', models.CharField(default='', max_length=50, verbose_name='Encoding')),
            ],
            options={
                'verbose_name': 'Ввод url-ов',
                'verbose_name_plural': 'Ввод url-ов',
            },
        ),
    ]
