# Generated by Django 2.2.7 on 2019-11-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_input_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='input_time',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='search_encoding',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='search_h1',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='search_title',
        ),
    ]
