# Generated by Django 2.2.7 on 2019-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191110_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_url', models.CharField(max_length=50)),
                ('save_title', models.CharField(max_length=50)),
                ('save_h1', models.CharField(max_length=50)),
                ('save_encoding', models.CharField(max_length=50)),
            ],
        ),
    ]
